### ISSUE TITLE
Pressing button 8 in mode 0

### ISSUE THREAD

**Issue by XanderBert** [TheLastMillennial/ti84plusce-autohotkey#1]
When button 8 is pressed in mode 0 Microsoft Office is started. when office is uninstalled it opens: https://www.office.com/?from=OfficeKey. Using the latest release of CEyboard

**Comment by XanderBert** [comment]
i see this is allready a fixed and known issue.

**Comment by TheLastMillennial** [comment]
Glad you got it fixed! For those that encounter the same issue, be sure to read the [troubleshooting section](https://github.com/TheLastMillennial/CEyboard#troubleshooting) of the readme.
