### ISSUE TITLE
equal short cut?

### ISSUE THREAD

**Issue by MintDiamond** [TheLastMillennial/ti84plusce-autohotkey#2]
Could you make and equal sign key? I think i would be use for coding
like 2nd Enter or Alpha Enter.
ill take a look at the code to see if i can find where it would be, still very new do coding.

**Comment by TheLastMillennial** [comment]
Already committed, I just need to push out a new release.

**Comment by TheLastMillennial** [comment]
Fixed with [b2c9655](https://github.com/TheLastMillennial/CEyboard/commit/b2c96552e6da70a6b4dfcd86888b9dbdc2959b75)
Download the new[ version 1.1.4](https://github.com/TheLastMillennial/CEyboard/releases/tag/v1.1.4)
